import { AdminShell } from "@/components/admin-shell";
import { createCategory, deleteCategory, updateCategory } from "@/app/admin/actions";
import { prisma } from "@/lib/db";

const errors: Record<string, string> = { "invalid-category": "Nama kategori belum valid.", "duplicate-category": "Nama atau slug kategori sudah digunakan.", "category-in-use": "Kategori masih dipakai kendaraan dan tidak dapat dihapus." };

export default async function AdminCategoriesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [{ error }, categories] = await Promise.all([searchParams, prisma.category.findMany({ include: { _count: { select: { vehicles: true } } }, orderBy: { name: "asc" } })]);
  return <AdminShell active="/admin/kategori"><section className="border-b border-[#E1E6EC] pb-6"><p className="text-sm font-semibold text-[#245FD4]">Master data</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Kategori kendaraan</h1><p className="mt-2 text-sm text-[#59687B]">Kelompokkan armada agar kendaraan mudah dikelola dan ditemukan pelanggan.</p></section>{error && errors[error] ? <p role="alert" className="mt-5 rounded-lg bg-[#FDE5E7] px-4 py-3 text-sm font-medium text-[#B42318]">{errors[error]}</p> : null}<section className="mt-6 rounded-xl border border-[#E1E6EC] bg-white p-5"><h2 className="font-bold">Tambah kategori</h2><form action={createCategory} className="mt-4 flex flex-col gap-3 sm:flex-row"><input name="name" required placeholder="Contoh: SUV Premium" className="flex-1 rounded-lg border border-[#DDE5EB] px-3 py-2 text-sm" /><input name="slug" placeholder="Slug opsional" className="flex-1 rounded-lg border border-[#DDE5EB] px-3 py-2 text-sm" /><button type="submit" className="rounded-lg bg-[#245FD4] px-4 py-2 text-sm font-semibold text-white">Simpan kategori</button></form></section><section className="mt-6 overflow-hidden rounded-xl border border-[#E1E6EC] bg-white"><div className="border-b border-[#EDF0F3] px-5 py-4"><h2 className="font-bold">Kategori ({categories.length})</h2></div><div className="divide-y divide-[#EDF0F3]">{categories.map((category) => <div key={category.id} className="grid gap-3 px-5 py-4 md:grid-cols-[1fr_1fr_auto]"><form action={updateCategory} className="contents"><input type="hidden" name="id" value={category.id} /><input name="name" defaultValue={category.name} className="rounded-lg border border-[#DDE5EB] px-3 py-2 text-sm" /><input name="slug" defaultValue={category.slug} className="rounded-lg border border-[#DDE5EB] px-3 py-2 text-sm" /><div className="flex items-center gap-3"><span className="text-xs text-[#66758A]">{category._count.vehicles} kendaraan</span><button type="submit" className="text-sm font-semibold text-[#245FD4]">Simpan</button></div></form><form action={deleteCategory} className="md:col-span-3"><input type="hidden" name="id" value={category.id} /><button type="submit" disabled={category._count.vehicles > 0} className="text-xs font-semibold text-[#C23B4A] disabled:text-[#AEB8C8]">Hapus kategori</button></form></div>)}</div></section></AdminShell>;
}