import Link from "next/link";
import { AdminShell } from "@/components/admin-shell";
import { prisma } from "@/lib/db";

const rupiah = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const statusLabels = { PENDING_PAYMENT: "Menunggu pembayaran", AWAITING_VERIFICATION: "Menunggu verifikasi", CONFIRMED: "Dikonfirmasi", ACTIVE: "Aktif", COMPLETED: "Selesai", CANCELLED: "Dibatalkan", REJECTED: "Ditolak" };

export default async function AdminDashboardPage() {
  const [vehicleCount, availableCount, customerCount, pendingDocs, bookings, paymentTotals] = await Promise.all([
    prisma.vehicle.count(),
    prisma.vehicle.count({ where: { status: "AVAILABLE" } }),
    prisma.user.count({ where: { role: "CUSTOMER" } }),
    prisma.identityDoc.count({ where: { status: "PENDING" } }),
    prisma.booking.findMany({ take: 6, orderBy: { createdAt: "desc" }, include: { user: { select: { name: true } }, vehicle: { select: { name: true } } } }),
    prisma.payment.aggregate({ where: { status: "PAID" }, _sum: { amount: true } }),
  ]);
  const metrics = [["Total armada", String(vehicleCount), "/admin/kendaraan"], ["Armada tersedia", String(availableCount), "/admin/kendaraan"], ["Pelanggan", String(customerCount), "/admin/pelanggan"], ["Dokumen pending", String(pendingDocs), "/admin/verifikasi"], ["Pembayaran diterima", rupiah.format(paymentTotals._sum.amount ?? 0), "/admin/transaksi"]] as const;
  return <AdminShell active="/admin"><section className="flex flex-col justify-between gap-4 border-b border-[#E1E6EC] pb-6 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[#245FD4]">Dashboard</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Pusat operasional RentGo</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#59687B]">Ringkasan ini dihitung langsung dari data armada, pelanggan, dokumen, booking, dan pembayaran.</p></div><Link href="/admin/kendaraan" className="w-fit rounded-lg bg-[#245FD4] px-4 py-2.5 text-sm font-semibold text-white">Kelola armada</Link></section><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label, value, href]) => <Link key={label} href={href} className="rounded-xl border border-[#E1E6EC] bg-white p-5 hover:border-[#9DB9EE]"><p className="text-sm text-[#66758A]">{label}</p><p className="mt-3 text-2xl font-bold text-[#17263B]">{value}</p></Link>)}</section><section className="mt-6 overflow-hidden rounded-xl border border-[#E1E6EC] bg-white"><div className="flex items-center justify-between border-b border-[#EDF0F3] px-5 py-4"><div><h2 className="font-bold">Booking terbaru</h2><p className="mt-1 text-xs text-[#66758A]">Data terbaru dari database.</p></div><Link href="/admin/pemesanan" className="text-sm font-semibold text-[#245FD4]">Lihat semua</Link></div>{bookings.length ? <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-[#F8FAFC] text-xs text-[#526177]"><tr><th className="px-5 py-3">Kode</th><th className="px-5 py-3">Pelanggan</th><th className="px-5 py-3">Kendaraan</th><th className="px-5 py-3">Total</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-[#EDF0F3]">{bookings.map((booking) => <tr key={booking.id}><td className="px-5 py-4 font-semibold text-[#245FD4]">{booking.code}</td><td className="px-5 py-4">{booking.user.name}</td><td className="px-5 py-4 text-[#526177]">{booking.vehicle.name}</td><td className="px-5 py-4">{rupiah.format(booking.totalAmount)}</td><td className="px-5 py-4 text-[#526177]">{statusLabels[booking.status]}</td></tr>)}</tbody></table></div> : <p className="px-5 py-10 text-sm text-[#66758A]">Belum ada booking.</p>}</section></AdminShell>;
}