"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";

type AdminSection = "kendaraan" | "kategori" | "pemesanan" | "transaksi" | "pelanggan" | "verifikasi" | "laporan";

const navigation = [
  ["Dashboard", "/admin"], ["Kendaraan", "/admin/kendaraan"], ["Kategori", "/admin/kategori"], ["Pemesanan", "/admin/pemesanan"], ["Transaksi", "/admin/transaksi"], ["Pelanggan", "/admin/pelanggan"], ["Verifikasi dokumen", "/admin/verifikasi"], ["Laporan", "/admin/laporan"],
] as const;

const content: Record<AdminSection, { title: string; description: string; action: string; columns: string[]; rows: string[][]; filters: string[] }> = {
  kendaraan: { title: "Kendaraan", description: "Kelola armada, harga sewa, dan status kesiapan kendaraan.", action: "Tambah kendaraan", filters: ["Semua status", "Semua kategori"], columns: ["Kendaraan", "Kategori", "Harga / hari", "Status", "Aksi"], rows: [["Toyota Avanza", "Mobil", "Rp 350.000", "Tersedia", "Atur"], ["Honda Brio", "Mobil", "Rp 280.000", "Sedang disewa", "Atur"], ["Honda Vario 160", "Motor", "Rp 150.000", "Tersedia", "Atur"], ["Toyota Innova", "Mobil", "Rp 550.000", "Perawatan", "Atur"]] },
  kategori: { title: "Kategori kendaraan", description: "Kelompokkan armada agar pelanggan lebih mudah menemukan kendaraan.", action: "Tambah kategori", filters: ["Semua kategori"], columns: ["Kategori", "Jumlah kendaraan", "Deskripsi", "Status", "Aksi"], rows: [["Mobil", "14 kendaraan", "Kendaraan roda empat", "Aktif", "Edit"], ["Motor", "10 kendaraan", "Kendaraan roda dua", "Aktif", "Edit"]] },
  pemesanan: { title: "Pemesanan", description: "Tinjau booking masuk dan tindak lanjuti pesanan yang memerlukan keputusan.", action: "Buat pemesanan", filters: ["Semua status", "Minggu ini"], columns: ["ID booking", "Pelanggan", "Kendaraan", "Periode sewa", "Status", "Aksi"], rows: [["BKG-0428", "Budi Santoso", "Toyota Avanza", "16–19 Sep", "Menunggu verifikasi", "Tinjau"], ["BKG-0427", "Nadia Putri", "Honda Brio", "16–18 Sep", "Dikonfirmasi", "Tinjau"], ["BKG-0426", "Rizky Pratama", "Honda Vario 160", "15–20 Sep", "Sedang disewa", "Tinjau"]] },
  transaksi: { title: "Transaksi", description: "Pantau pembayaran DP, pelunasan, dan pengembalian dana pelanggan.", action: "Catat transaksi", filters: ["Semua pembayaran", "Bulan ini"], columns: ["ID transaksi", "Booking", "Pelanggan", "Jumlah", "Status", "Aksi"], rows: [["TRX-1028", "BKG-0428", "Budi Santoso", "Rp 498.750", "DP dibayar", "Periksa"], ["TRX-1027", "BKG-0427", "Nadia Putri", "Rp 700.000", "Lunas", "Periksa"], ["TRX-1026", "BKG-0426", "Rizky Pratama", "Rp 285.000", "DP dibayar", "Periksa"]] },
  pelanggan: { title: "Pelanggan", description: "Lihat data pelanggan dan kelengkapan verifikasi dokumennya.", action: "Tambah pelanggan", filters: ["Semua verifikasi"], columns: ["Pelanggan", "Kontak", "Dokumen", "Riwayat sewa", "Aksi"], rows: [["Budi Santoso", "budi@email.com", "Menunggu", "3 kali", "Lihat"], ["Nadia Putri", "nadia@email.com", "Terverifikasi", "5 kali", "Lihat"], ["Rizky Pratama", "rizky@email.com", "Terverifikasi", "2 kali", "Lihat"]] },
  verifikasi: { title: "Verifikasi dokumen", description: "Periksa KTP dan SIM pelanggan sebelum pesanan dapat diproses.", action: "Lihat antrean", filters: ["Menunggu verifikasi"], columns: ["Pelanggan", "KTP", "SIM", "Dikirim", "Aksi"], rows: [["Budi Santoso", "Tersedia", "Tersedia", "14 Sep 2026", "Periksa"], ["Dewi Kartika", "Tersedia", "Tersedia", "14 Sep 2026", "Periksa"], ["Fajar Nugraha", "Tersedia", "Belum unggah", "13 Sep 2026", "Periksa"]] },
  laporan: { title: "Laporan", description: "Ringkasan performa rental untuk periode yang Anda pilih.", action: "Export laporan", filters: ["Bulan ini", "Semua transaksi"], columns: ["ID transaksi", "Pelanggan", "Kendaraan", "Total", "Status", "Tanggal"], rows: [["TRX-1027", "Nadia Putri", "Honda Brio", "Rp 700.000", "Lunas", "14 Sep 2026"], ["TRX-1025", "Siti Rahma", "Toyota Innova", "Rp 1.650.000", "Lunas", "13 Sep 2026"], ["TRX-1023", "Andi Pratama", "Toyota Avanza", "Rp 997.500", "Lunas", "12 Sep 2026"]] },
};

function Icon({ name, className = "h-5 w-5" }: { name: "menu" | "bell" | "plus" | "filter" | "download" | "refresh"; className?: string }) {
  const paths = { menu: <path d="M4 6h16M4 12h16M4 18h16" />, bell: <><path d="M18 16v-5a6 6 0 0 0-12 0v5l-2 2h16l-2-2Z" /><path d="M10 21h4" /></>, plus: <path d="M12 5v14M5 12h14" />, filter: <path d="M4 6h16M7 12h10M10 18h4" />, download: <><path d="M12 3v11" /><path d="m8 10 4 4 4-4" /><path d="M5 21h14" /></>, refresh: <><path d="M20 11a8 8 0 1 0 1 5" /><path d="M20 4v7h-7" /></> };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" className={className} aria-hidden="true">{paths[name]}</svg>;
}

function AdminSidebar({ active }: { active: AdminSection }) {
  return <aside className="fixed inset-y-0 left-0 z-30 hidden w-[260px] border-r border-[#e5eaf1] bg-white lg:flex lg:flex-col">
    <div className="flex h-[76px] items-center gap-3 border-b border-[#e5eaf1] px-7"><Image src="/referensi/Logo%20RentGo.svg" alt="RentGo" width={174} height={58} className="h-5 w-auto" /><span className="rounded bg-[#eaf1ff] px-2 py-1 text-[10px] font-semibold text-[#245fd4]">Admin</span></div>
    <nav className="flex-1 px-4 py-6" aria-label="Navigasi admin"><p className="mb-3 px-3 text-xs font-medium text-[#7a8799]">Menu utama</p><div className="space-y-1">{navigation.map(([label, href]) => { const isActive = href.endsWith(active); return <Link key={href} href={href} className={"flex h-11 items-center rounded-lg px-3 text-sm font-medium " + (isActive ? "bg-[#245fd4] text-white shadow-[0_8px_20px_rgba(36,95,212,.16)]" : "text-[#526177] hover:bg-[#eef4ff] hover:text-[#245fd4]")}>{label}</Link>; })}</div></nav>
    <div className="border-t border-[#e5eaf1] p-4"><div className="rounded-xl bg-[#f7f9fc] p-3"><p className="text-sm font-semibold text-[#203047]">Raka Admin</p><p className="mt-1 text-xs text-[#7a8799]">admin@rentgo.id</p></div></div>
  </aside>;
}

export function AdminWorkspace({ section }: { section: AdminSection }) {
  const page = content[section];
  const [query, setQuery] = useState("");
  const [toast, setToast] = useState("");
  const [loading, setLoading] = useState(false);
  const rows = useMemo(() => page.rows.filter((row) => row.join(" ").toLowerCase().includes(query.toLowerCase())), [page.rows, query]);
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2500); }
  function reload() { setLoading(true); window.setTimeout(() => setLoading(false), 650); }
  return <div className="min-h-screen bg-white text-[#17263b]"><AdminSidebar active={section} />
    <header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-[#e5eaf1] bg-white/95 px-5 backdrop-blur lg:ml-[260px] lg:px-9"><Link href="/admin" className="lg:hidden"><Image src="/referensi/Logo%20RentGo.svg" alt="RentGo" width={174} height={58} className="h-5 w-auto" /></Link><div className="hidden items-center gap-2 text-sm text-[#647286] lg:flex"><Icon name="menu" className="h-4 w-4" /><span>Operasional RentGo</span></div><div className="flex items-center gap-3"><button type="button" onClick={() => notify("Tidak ada notifikasi baru.")} aria-label="Notifikasi" className="grid h-10 w-10 place-items-center rounded-full border border-[#e1e6ed] text-[#45546a]"><Icon name="bell" /></button><span className="grid h-10 w-10 place-items-center rounded-full bg-[#eaf1ff] text-xs font-bold text-[#245fd4]">RA</span></div></header>
    <main className="pb-24 lg:ml-[260px] lg:pb-10"><div className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8 lg:px-9"><section className="flex flex-col gap-4 border-b border-[#edf0f3] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-[28px] font-bold tracking-[-.035em] text-[#122139] sm:text-[32px]">{page.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#59687b]">{page.description}</p></div><button type="button" onClick={() => notify(section === "laporan" ? "Laporan dummy telah disiapkan untuk diunduh." : page.action + " siap dibuka setelah backend terhubung.")} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[#245fd4] px-4 text-sm font-semibold text-white"><Icon name={section === "laporan" ? "download" : "plus"} className="h-4 w-4" />{page.action}</button></section>
      <section className="mt-6 rounded-xl border border-[#e1e6ec] bg-white"><div className="flex flex-col gap-3 border-b border-[#edf0f3] p-4 sm:flex-row sm:items-center sm:justify-between"><label className="flex h-10 min-w-0 flex-1 items-center rounded-lg border border-[#dfe5eb] px-3 sm:max-w-md"><span className="sr-only">Cari data</span><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none placeholder:text-[#8c99aa]" placeholder={"Cari " + page.title.toLowerCase() + "..."} /></label><div className="flex flex-wrap gap-2"><button type="button" onClick={() => notify("Filter akan memakai data backend saat tersedia.")} className="inline-flex h-10 items-center gap-2 rounded-lg border border-[#dfe5eb] px-3 text-sm font-medium text-[#526177]"><Icon name="filter" className="h-4 w-4" />{page.filters[0]}</button><button type="button" onClick={reload} className="inline-flex h-10 w-10 items-center justify-center rounded-lg border border-[#dfe5eb] text-[#526177]" aria-label="Muat ulang"><Icon name="refresh" className="h-4 w-4" /></button></div></div>
      {loading ? <div className="space-y-3 p-5" aria-label="Memuat data">{[1, 2, 3].map((item) => <div key={item} className="h-12 animate-pulse rounded-lg bg-[#f2f5f9]" />)}</div> : rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-[#f8fafc] text-[11px] font-semibold text-[#526177]"><tr>{page.columns.map((column) => <th key={column} className="px-5 py-3">{column}</th>)}</tr></thead><tbody className="divide-y divide-[#edf0f3]">{rows.map((row) => <tr key={row[0]} className="text-sm hover:bg-[#fbfcff]">{row.map((cell, index) => <td key={cell} className={"px-5 py-4 " + (index === row.length - 1 ? "font-semibold text-[#245fd4]" : index === row.length - 2 ? "font-medium text-[#34445b]" : "text-[#526177]")}>{cell}</td>)}</tr>)}</tbody></table></div> : <div className="grid min-h-64 place-items-center px-5 text-center"><div><p className="text-base font-semibold text-[#25354b]">Data tidak ditemukan</p><p className="mt-2 text-sm text-[#66758a]">Ubah kata pencarian atau kosongkan filter untuk melihat data lain.</p><button type="button" onClick={() => setQuery("")} className="mt-4 text-sm font-semibold text-[#245fd4]">Bersihkan pencarian</button></div></div>}</section><p className="mt-4 text-xs leading-5 text-[#7a8799]">Tampilan menggunakan data dummy. Aksi simpan, ubah, dan hapus akan dihubungkan ke backend pada tahap berikutnya.</p></div></main>
    <nav className="fixed inset-x-3 bottom-3 z-30 grid grid-cols-4 rounded-2xl border border-[#dfe5eb] bg-white/95 p-1.5 shadow-[0_10px_35px_rgba(20,38,65,.15)] backdrop-blur lg:hidden">{navigation.slice(0, 4).map(([label, href]) => <Link key={href} href={href} className={"rounded-xl py-2 text-center text-[10px] font-semibold " + (href.endsWith(section) ? "bg-[#eaf1ff] text-[#245fd4]" : "text-[#4c5b70]")}>{label}</Link>)}</nav>{toast ? <div role="status" className="fixed bottom-20 right-4 z-50 rounded-xl bg-[#17263b] px-4 py-3 text-sm font-medium text-white shadow-lg lg:bottom-6">{toast}</div> : null}</div>;
}
